### PR TITLE
Auth

### PR DESCRIPTION
**Pull request by jakazzy**
#### What does this PR do?
This Pull request adds authentication with email and password to the exercise

#### Description of Task to be completed?
Create authentication using user email and password

#### How should this be manually tested?
1. Set up the project following the steps in the README.md
2. Test the auth endpoint

#### Any background context you want to provide?
none
#### What are the relevant user stories?
https://github.com/jakazzy/exercise-tracker/issues/7

### CODE REVIEW

**Comment by jakazzy** [comment]
@kofiasare i just updated the other endpoints

**Comment by jakazzy** [comment]
@kofiasare I have also added a folder called endpoints the contains the test routes

**Review by kofiasare — COMMENTED** [review]
Hi Jida,

You can dry up your code in the exercise controller. I observer that because of the nested routes i.e `/users/userID/exercise/id`. 

You always have to be finding the user for each action of the controller.

What can be  done is to extract the code for getting the user into a function 
e.g setUser() 
note that it is not an action of the controller so keep it out of the export. You just need to call it in any action that requires it

```javascript
 // in errors.js

 export class RecordNotFoundError extends Error { 
   constructor(message) {
     super(message)
     this.name = "RecordNotFoundError"
     this.code = 404
    }
 }
```
```javascript
 //  exerciseController.js

 create: async(req, res) => {
   try {
     // maybe some stuff first
     const user = await setUser()
   catch(e) {
     if (e.code) { 
       res.status(e.code).send({ message: e.message } )
     else {
       // ...
     }
    }
 }
```

```javascript
// outside the export

import { RecordNotFoundError } from 'path/to/errors.js'

function setUser(id) {
  return new Promise(async (resolve, reject) => {
    const user = await userModel.find(id)
    return user ? resolve(user) : reject(new RecordNotFoundError('User not found.'))
  })
}
```
Try this let's see

**Comment by jakazzy** [comment]
> Hi Jida,
> 
> You can dry up your code in the exercise controller. I observer that because of the nested routes i.e `/users/userID/exercise/id`.
> 
> You always have to be finding the user for each action of the controller.
> 
> What can be done is to extract the code for getting the user into a function
> e.g setUser()
> note that it is not an action of the controller so keep it out of the export. You just need to call it in any action that requires it
> 
> ```js
> function setUser(id) {
>    return new Promise(async (resolve, reject) => {
>        const user = await userModel.find(id)
>        return user ? resolve(user) : reject(new Error('User not found')
>    })
> }
> ```

sure noted

**Comment by jakazzy** [comment]
@kofiasare sure noted

**Pull request merged**
